### ISSUE TITLE
NullPointerException in LocationServiceHelper

### ISSUE THREAD

**Issue by Kahtaf** [OpenLocate/openlocate-android#55]
I just upgraded to 0.1.10 and received a NPE almost immediately. Nexus 6P, Android Oreo. 

```
10-20 15:09:27.812 2412-2412/com.bitspice.automate E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.bitspice.automate, PID: 2412
                                                                     java.lang.RuntimeException: Unable to start service com.openlocate.android.core.LocationService@35b9fd0 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                         at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
                                                                         at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                         at com.openlocate.android.core.LocationServiceHelper.setValues(LocationServiceHelper.java:146)
                                                                         at com.openlocate.android.core.LocationServiceHelper.onStartCommand(LocationServiceHelper.java:97)
                                                                         at com.openlocate.android.core.LocationService.onStartCommand(LocationService.java:57)
                                                                         at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
                                                                         at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                         at android.os.Looper.loop(Looper.java:164) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
10-20 15:09:27.815 2412-2412/com.bitspice.automate E/UncaughtException: java.lang.RuntimeException: Unable to start service com.openlocate.android.core.LocationService@35b9fd0 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
                                                                            at android.app.ActivityThread.-wrap20(Unknown Source:0)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                            at com.openlocate.android.core.LocationServiceHelper.setValues(LocationServiceHelper.java:146)
                                                                            at com.openlocate.android.core.LocationServiceHelper.onStartCommand(LocationServiceHelper.java:97)
                                                                            at com.openlocate.android.core.LocationService.onStartCommand(LocationService.java:57)
                                                                            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
                                                                            at android.app.ActivityThread.-wrap20(Unknown Source:0) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by kurabi** [comment]
Hi @Kahtaf master only has v0.1.9. Where did you pick up v0.1.10?

**Comment by Kahtaf** [comment]
I copied the dependency from the README.md, which is currently listed as 0.1.10. It synced just fine so I assumed I was using 0.1.10. 

`compile 'com.openlocate:openlocate:0.1.10@aar'`

**Comment by kurabi** [comment]
Resolved.
