### ISSUE TITLE
jacoco.exec (Read-only file system)

### ISSUE THREAD

**Issue by ndjemam** [OpenLocate/openlocate-android#95]
Hi guys: 
I run the example he gives me this error

10-01 11:07:03.520 9373-9373/com.openlocate.example W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
10-01 11:07:03.521 9373-9373/com.openlocate.example W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
        at com.openlocate.android.core.OpenLocate$Endpoint.$jacocoInit(Unknown Source:14)
        at com.openlocate.android.core.OpenLocate$Endpoint.<clinit>(Unknown Source:0)
        at com.openlocate.android.core.OpenLocate$Endpoint.builder(Unknown Source:0)
        at com.openlocate.example.ExampleApplication.onCreate(ExampleApplication.java:18)

**Comment by kurabi** [comment]
I can’t reproduce this issue. Can you provide more details on your Android build configuration?

**Comment by kurabi** [comment]
Closed due to no response.
