### ISSUE TITLE
Crashes in LocationTable#size and LocationTable#get

### ISSUE THREAD

**Issue by SergeyPoluyanov** [OpenLocate/openlocate-android#97]
OpenLocate version `1.2.1`

Crash logs:

```
Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
       at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:650)
       at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:886)
       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:874)
       at android.database.DatabaseUtils.queryNumEntries(DatabaseUtils.java:851)
       at android.database.DatabaseUtils.queryNumEntries(DatabaseUtils.java:819)
       at com.openlocate.android.core.LocationTable.size(LocationTable.java:114)
       at com.openlocate.android.core.LocationDatabase.size(LocationDatabase.java:58)
       at com.openlocate.android.core.LocationServiceHelper$LocationListener.onLocationChanged(LocationServiceHelper.java:382)
       at com.google.android.gms.internal.location.zzay.notifyListener(Unknown Source)
       at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
       at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

```
Fatal Exception: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/{app package name}/databases/OpenLocate.db
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1603)
       at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1505)
       at com.openlocate.android.core.LocationTable.add(LocationTable.java:87)
       at com.openlocate.android.core.LocationDatabase.add(LocationDatabase.java:43)
       at com.openlocate.android.core.LocationServiceHelper$LocationListener.onLocationChanged(LocationServiceHelper.java:371)
       at com.google.android.gms.internal.location.zzay.notifyListener(Unknown Source)
       at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
       at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by kurabi** [comment]
Please upgrade to 2.0.0
